### ISSUE TITLE
My admins can not see the tickets

### ISSUE THREAD

**Issue by Alexxxunchained** [ir8scripts/ir8-tickets#1]
My admins can not see the tickets, even I set it up correctlly like permission admin something...

**Comment by RobertGrubb** [comment]
What framework are you using with it?

**Comment by Alexxxunchained** [comment]
QBX

**Comment by RobertGrubb** [comment]
@Alexxxunchained Care try with the new release? Note: Read the README as the permissions setup has changed. (Apologies for the late reply, life has been demanding lately)
